# Generated by Django 5.0.1 on 2024-03-04 14:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_news_options_news_slug_alter_news_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, null=True, verbose_name='Link'),
        ),
    ]
