# Generated by Django 5.0.1 on 2024-03-07 16:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_news_options_alter_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, null=True, verbose_name='category_link'),
        ),
    ]
