# Generated by Django 5.0.1 on 2024-03-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
