# Generated by Django 5.0.1 on 2024-02-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
